### ISSUE TITLE
Code to TF 2.0 instead of 1.14

### ISSUE THREAD

**Issue by jmarrietar** [google-research/remixmatch#10]
Hi, I really appreciate that this code is open source. But I have a question, as the papers seem fairly recent, why are you guys using TF 1.14 instead of newer versions?. 

Thank you very much!

**Comment by carlini** [comment]
We started this line of work with the MixMatch paper, where work really picked up in January 2019---before TF2 was public. We've since continued using this framework for the remaining two papers in order to ensure all our baselines are comparable and use the same implementations of everything.

**Comment by jmarrietar** [comment]
Thanks for the answer @carlini !. I assume there are no plans to upgrade the code to TF 2.0 at this time I guess?. 

Cheers,

**Comment by carlini** [comment]
David has done some great work converting this line of work to JAX: https://github.com/google/objax/tree/master/examples/classify/semi_supervised/img.
