### ISSUE TITLE
How to reproduce the results on cifar10 with 40 label data

### ISSUE THREAD

**Issue by luolanfeixue** [google-research/remixmatch#13]
as the readme, I run the command

python cat/cat_remixmath.py --batch=2048 --dataset=cifar10.1@40-1 --K=1 --w_rot=2 --warmup_kimg=8192

and Finally, I got the folder

./experiments/cifar10.d.d.d.1@40-1/CTAugment_depth2_th0.80_decay0.990/CATReMixMatch_K1_archresnet_batch2048_beta0.75_filter32_lr0.002__nclass10_redux1st_repeat4_scales3_use_dmTrue_use_xeTrue_w_kl0.5_w_match1.5_w_rot2.0_warmup_kimg8193_wd0.02/

and then I run 

python ./scripts/extract_accuracy.py "the upper folder"

I got this accuracy

{
  "last01": 66.66,
  "last10": 66.1199,
  "last20": 66.06
  "last50":66.43
}

Why I can't get the result of the paper (84.92), how should I set the parameters?

**Comment by carlini** [comment]
This value of --batch is quite big, is there a reason you changed it?

**Comment by luolanfeixue** [comment]
just want to accelerate, it should be 64?

**Comment by carlini** [comment]
Yeah. I'd start by running with the hyperparameters we suggest in the paper to reproduce our results. Then you can try to tweak things to get it going faster.
