### ISSUE TITLE
Not understanding what these two lines mean?

### ISSUE THREAD

**Issue by SungFeng-Huang** [google-research/remixmatch#3]
I'm studying your code and trying to figure out how to train the weights of CTAugment, but I couldn't understand what these two lines are trying to do:
https://github.com/google-research/remixmatch/blob/f7061ebf055227cbeb5c6fced1ce054e0ceecfcd/libml/ctaugment.py#L74-L75
As far as I understand, each parameter of each transform is divided into bins.
For example, the parameter M of the rescaling transform should be divided into 6 bins, corresponding to 6 methods mentioned in Appendix C. 
So, for the parameter M, its rate would be initialized to [1,1,1,1,1,1] according to line 50:
https://github.com/google-research/remixmatch/blob/f7061ebf055227cbeb5c6fced1ce054e0ceecfcd/libml/ctaugment.py#L50
, then after line 74, p would still be six ones, but after line 75, segments would be [2,2,2,2,2], which means line 76 could only choose from np.arange(5):
https://github.com/google-research/remixmatch/blob/f7061ebf055227cbeb5c6fced1ce054e0ceecfcd/libml/ctaugment.py#L76
This would be kind of weird to me since I thought it should choose from probabilities of size 6 instead of 5, according to 6 bins.

Looking forward to any detailed explanation. Thanks!

**Comment by david-berthelot** [comment]
The bins are treated as segments, it's not really necessary and I think we simplified it in fixmatch code. But basically the idea is to call the interval between bins a segment, this allows to model the values as piece-wise linear.

**Comment by SungFeng-Huang** [comment]
Now I've seen the code in FixMatch and it seems to meet my original thought. Thanks for answering!
