### ISSUE TITLE
What's the meaning of "probe" and where is the weak transform?

### ISSUE THREAD

**Issue by NovaMind-Z** [google-research/remixmatch#5]
Hi, I do appreciate this excellent work. However, I'm still confused about two places in the code.　
1. When taking the ctaugment transformation, I found there is a switch  controlled by the bool "probe", what does this mean? I found that when you augment the labeled images, the "probe" is true, and "probe" is false for unlabeled images. Why?
2. According to the paper, the unlabeled images should be weakly transformed. But I found in this line (line208) that, you just use the original input x[0] to represent the weakly transformation, am I right?
![image](https://user-images.githubusercontent.com/42997811/77065680-b6662f00-6a1c-11ea-83cb-afe8fb115fd2.png)
Thanks in advance.

**Comment by david-berthelot** [comment]
The probe is when we sample uniformly the policy in order to update CTAugment probabilities (last paragraph of section 3.2.2 in the paper), probe is True when we process a labeled image.
An input image is always weakly augmented (the `x` variable). For unlabeled images, probe is False. And as you can see the first augmented image is x[0] (line 208), meaning the identity policy.

**Comment by NovaMind-Z** [comment]
> The probe is when we sample uniformly the policy in order to update CTAugment probabilities (last paragraph of section 3.2.2 in the paper), probe is True when we process a labeled image.
> An input image is always weakly augmented (the `x` variable). For unlabeled images, probe is False. And as you can see the first augmented image is x[0] (line 208), meaning the identity policy.

I do appreciate your reply! I'm trying to use pytorch to reproduce the results on paper, and now it seems much better. Thanks again!

**Comment by carlini** [comment]
Closing this issue.

**Comment by carlini** [comment]
(With the comment that if you are sure you want to reproduce this paper, go ahead, but our more recent FixMatch paper is both simpler and gives better results on almost all datasets.)
