### ISSUE TITLE
What are the most important things to reproduce the result on my own dataset?

### ISSUE THREAD

**Issue by guotong1988** [google-research/remixmatch#6]
UDA(https://github.com/google-research/uda) could achieve good accuracy by only 20 training data on text classification. But I find it is hard to reproduce the result on my own dataset.

So I want to know the reason why UDA or ReMixMatch works. And I want to know what is the most important thing to reproduce the result.

@carlini  Thank you very much.

**Comment by carlini** [comment]
I have responded to this question in the MixMatch repository
https://github.com/google-research/mixmatch/issues/27

The answer here is unlikely to be different.

**Comment by guotong1988** [comment]
Thank you.

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/84100114-cbf85d00-aa3d-11ea-83b3-c4054b58171c.png)
